include theos/makefiles/common.mk

TWEAK_NAME = zeppelin_uikit
zeppelin_uikit_FILES = Tweak.xm
zeppelin_uikit_CFLAGS = -I../include
zeppelin_uikit_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk
