include theos/makefiles/common.mk

TWEAK_NAME = zeppelin_sb
zeppelin_sb_FILES  = Tweak.xm ZPImageServer.m Categories/NSString+ZPAdditions.m
zeppelin_sb_CFLAGS = -I../include
zeppelin_sb_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk
