#!/bin/bash

# Move Zeppelin logos to /var/stash on the data partition
echo "Stashing Logos..."

if [ ! -L "/Library/Zeppelin" ]; then
    /usr/libexec/cydia/move.sh /Library/Zeppelin
fi

if [ -d /Library/Zeppelin ]; then
	echo "Repairing permissions for themes..."
	chown -R mobile:mobile /Library/Zeppelin
	chmod -R 755 /Library/Zeppelin
	echo "Done"
fi

if [ -f /var/mobile/Library/Preferences/com.alexzielenski.zeppelin.plist ]; then
	echo "Repairing permissions for preferences..."
	chmod 755 /var/mobile/Library/Preferences/com.alexzielenski.zeppelin.plist
	chown mobile:mobile /var/mobile/Library/Preferences/com.alexzielenski.zeppelin.plist
	echo "Done"
fi
exit 0