#!/bin/bash

if [ -d /Library/Zeppelin ]; then
	echo "Repairing permissions for themes..."
	chown -R mobile:mobile /Library/Zeppelin
	chmod -R 755 /Library/Zeppelin
	echo "Done"
fi

if [ -f /var/mobile/Library/Preferences/com.alexzielenski.zeppelin.plist ]; then
	echo "Repairing permissions for preferences..."
	chmod 755 /var/mobile/Library/Preferences/com.alexzielenski.zeppelin.plist
	chown mobile:mobile /var/mobile/Library/Preferences/com.alexzielenski.zeppelin.plist
	echo "Done"
fi
exit 0